# Generated by Django 5.2.4 on 2025-07-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="symptoms",
            field=models.TextField(
                blank=True, help_text="Patient symptoms or reason for appointment"
            ),
        ),
    ]
